AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Search Photo Lambda
Resources:
  SearchPhotoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos1
      Handler: search-photos.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambda Functions/search-photos.py
      Description: 'Lambda function for Search Photo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::710827020694:role/testroleLambda'
      Events:
      Environment:
        Variables:
          REGION: us-east-1
  IndexPhotoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos1
      Handler: index.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambda Functions/index-photos.py
      Description: 'Lambda function for Index Photo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::710827020694:role/testroleLambda'
      Events:
      Environment:
        Variables:
          REGION: us-east-1
  