AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Search Photo Lambda
Resources:
  SearchPhotoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos2
      Handler: search-photos.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambda Functions/search-photos.py
      Description: 'Lambda function for Search Photo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::710827020694:role/service-role/search-photo-test-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - sg-0046592b
        SubnetIds:
          - subnet-3d799b1c
          - subnet-4349fe0e
  IndexPhotoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos2
      Handler: index-photos.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambda Functions/index-photos.py
      Description: 'Lambda function for Index Photo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::710827020694:role/service-role/index-photos-test-role'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
      VpcConfig:
        SecurityGroupIds:
          - sg-0046592b
        SubnetIds:
          - subnet-3d799b1c
          - subnet-4349fe0e
  Bucket1:
    Type: 'AWS::S3::Bucket'
  