AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Search Photo Lambda
Resources:
  SearchPhotoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambda Functions
      Description: 'Lambda function for Search Photo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::710827020694:role/service-role/AWSCodePipelineServiceRole-us-east-1-P1'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
  IndexPhotoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: detect_labels
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambda Functions
      Description: 'Lambda function for Index Photo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::710827020694:role/service-role/AWSCodePipelineServiceRole-us-east-1-P1'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1